version: '3.8'

services:
  app:
    container_name: image-management
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - sqlite-data:/app/db
      - ./public/uploads:/app/public/uploads

volumes:
  sqlite-data:
  uploads:
